GET_2290_SCHEDULE_1S_BY_MSG_ID=la.www4.irs.gov/a2a/mef/mime/Get2290Schedule1sByMsgID
GET_2290_SCHEDULE_1S=la.www4.irs.gov/a2a/mef/mime/Get2290Schedule1s
GET_2290_SCHEDULE_1=la.www4.irs.gov/a2a/mef/mime/Get2290Schedule1
GET_ACK=la.www4.irs.gov/a2a/mef/mime/GetAck
GET_ACK_NOTIFICATION=la.www4.irs.gov/a2a/mef/mime/GetAckNotification
GET_ACK_NOTIFICATIONS=la.www4.irs.gov/a2a/mef/mime/GetAckNotifications
GET_ACKS_BY_MSG_ID=la.www4.irs.gov/a2a/mef/mime/GetAcksByMsgID
GET_ACKS=la.www4.irs.gov/a2a/mef/mime/GetAcks
GET_NEW_2290_SCHEDULE_1S=la.www4.irs.gov/a2a/mef/mime/GetNew2290Schedule1s
GET_NEW_ACK_NOTIFICATIONS=la.www4.irs.gov/a2a/mef/mime/GetNewAckNotifications
GET_NEW_ACKS=la.www4.irs.gov/a2a/mef/mime/GetNewAcks
GET_NEW_SUBMISSIONS=la.www4.irs.gov/a2a/mef/mime/GetNewSubmissions
GET_NEW_SUBMISSIONS_STATUS=la.www4.irs.gov/a2a/mef/mime/GetNewSubmissionsStatus
GET_SUBMISSION=la.www4.irs.gov/a2a/mef/mime/GetSubmission
GET_SUBMISSIONS_BY_MSG_ID=la.www4.irs.gov/a2a/mef/mime/GetSubmissionsByMsgID
GET_SUBMISSIONS=la.www4.irs.gov/a2a/mef/mime/GetSubmissions
GET_SUBMISSIONS_STATUS=la.www4.irs.gov/a2a/mef/mime/GetSubmissionsStatus
GET_SUBMISSION_STATUS=la.www4.irs.gov/a2a/mef/mime/GetSubmissionStatus
SEND_SUBMISSIONS=la.www4.irs.gov/a2a/mef/mime/SendSubmissions
ETIN_RETRIEVAL=la.www4.irs.gov/a2a/mef/EtinRetrieval
ETIN_STATUS=la.www4.irs.gov/a2a/mef/EtinStatus
GET_STATE_PARTICIPANTS_LIST=la.www4.irs.gov/a2a/mef/GetStateParticipantsList
GET_SUBMISSION_RECONCILIATION_LIST=la.www4.irs.gov/a2a/mef/mime/GetSubmissionReconciliationList
LOGIN=la.www4.irs.gov/a2a/mef/Login
LOGOUT=la.www4.irs.gov/a2a/mef/Logout
SEND_ACKS=la.www4.irs.gov/a2a/mef/mime/SendAcks
SEND_SUBMISSION_RECEIPTS=la.www4.irs.gov/a2a/mef/mime/SendSubmissionReceipts

#MTOM ENABLED ENDPOINTS
GET_2290_SCHEDULE_1S_BY_MSG_ID_MTOM=la.www4.irs.gov/a2a/mef/mtom/Get2290Schedule1sByMsgID
GET_2290_SCHEDULE_1S_MTOM=la.www4.irs.gov/a2a/mef/mtom/Get2290Schedule1s
GET_2290_SCHEDULE_1_MTOM=la.www4.irs.gov/a2a/mef/mtom/Get2290Schedule1
GET_ACK_MTOM=la.www4.irs.gov/a2a/mef/mtom/GetAck
GET_ACK_NOTIFICATION_MTOM=la.www4.irs.gov/a2a/mef/mtom/GetAckNotification
GET_ACK_NOTIFICATIONS_MTOM=la.www4.irs.gov/a2a/mef/mtom/GetAckNotifications
GET_ACKS_BY_MSG_ID_MTOM=la.www4.irs.gov/a2a/mef/mtom/GetAcksByMsgID
GET_ACKS_MTOM=la.www4.irs.gov/a2a/mef/mtom/GetAcks
GET_NEW_2290_SCHEDULE_1S_MTOM=la.www4.irs.gov/a2a/mef/mtom/GetNew2290Schedule1s
GET_NEW_ACK_NOTIFICATIONS_MTOM=la.www4.irs.gov/a2a/mef/mtom/GetNewAckNotifications
GET_NEW_ACKS_MTOM=la.www4.irs.gov/a2a/mef/mtom/GetNewAcks
GET_NEW_SUBMISSIONS_MTOM=la.www4.irs.gov/a2a/mef/mtom/GetNewSubmissions
GET_NEW_SUBMISSIONS_STATUS_MTOM=la.www4.irs.gov/a2a/mef/mtom/GetNewSubmissionsStatus
GET_SUBMISSION_MTOM=la.www4.irs.gov/a2a/mef/mtom/GetSubmission
GET_SUBMISSIONS_BY_MSG_ID_MTOM=la.www4.irs.gov/a2a/mef/mtom/GetSubmissionsByMsgID
GET_SUBMISSIONS_MTOM=la.www4.irs.gov/a2a/mef/mtom/GetSubmissions
GET_SUBMISSIONS_STATUS_MTOM=la.www4.irs.gov/a2a/mef/mtom/GetSubmissionsStatus
GET_SUBMISSION_STATUS_MTOM=la.www4.irs.gov/a2a/mef/mtom/GetSubmissionStatus
SEND_SUBMISSIONS_MTOM=la.www4.irs.gov/a2a/mef/mtom/SendSubmissions
GET_SUBMISSION_RECONCILIATION_LIST_MTOM=la.www4.irs.gov/a2a/mef/mtom/GetSubmissionReconciliationList
SEND_ACKS_MTOM=la.www4.irs.gov/a2a/mef/mtom/SendAcks
SEND_SUBMISSION_RECEIPTS_MTOM=la.www4.irs.gov/a2a/mef/mtom/SendSubmissionReceipts