package com.irs.mef.dto;

import jakarta.validation.constraints.NotBlank;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDate;

/**
 * Request DTO for submitting tax returns to IRS MeF.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class SubmitRequest {

    /**
     * Submission ID (generated by transmitter)
     */
    @NotBlank(message = "Submission ID is required")
    private String submissionId;

    /**
     * Path to submission archive file (ZIP)
     */
    @NotBlank(message = "Submission file path is required")
    private String submissionFilePath;

    /**
     * Whether this is a production submission
     */
    private boolean productionMode = false;

    /**
     * Optional: Manifest file content
     */
    private String manifest;

    /**
     * Optional: Additional metadata
     */
    private String metadata;

    /**
     * EFIN - Electronic Filer Identification Number (required for manifest)
     */
    private String efin;

    /**
     * TIN - Taxpayer Identification Number/EIN (required for manifest)
     */
    private String tin;

    /**
     * Tax period begin date (recommended for employment tax forms like 941)
     */
    private LocalDate taxPeriodBegin;

    /**
     * Tax period end date (recommended for employment tax forms like 941)
     */
    private LocalDate taxPeriodEnd;
}
